# path to store model, output
# $output/
#   release/
# output: output/ # /grogu/user/yufeiy2/dex_afford/
output: /scratch2/jared/projects/affordances/human-affordances/aff-diff/output/


# path to store data
# $data/
#   hoi4d/
#     HOI4D_glide/
#     Sets/
# data: /home/yufeiy2/scratch/result/
data: /scratch2/jared/projects/affordances/human-affordances/aff-diff/data/


# path to store pretrained models
# $pretrain/
#   glide/
#     base_inpaint.pt
#   stable/
#     base_inpaint.pt
pretrain: /home/yufeiy2/scratch/pretrain/